import {
  Activity, AlertTriangle, BadgeCheck, BarChart3, Bell, BookOpen, Boxes, Building2, Calendar, Camera,
  CheckCircle2, Clipboard, ClipboardCheck, Clock, Cloud, Cpu, CreditCard, Database, DoorOpen, Download,
  Eye, FileText, Flag, GitBranch, GitMerge, Globe, Goal, Gauge, Hash, KeyRound, Landmark, Layers, Link2,
  Lock, Map, Monitor, Network, OctagonAlert, Package, PieChart, QrCode, Radio, Receipt, RefreshCw, Repeat,
  Route, ScanLine, Search, Send, Server, Settings, Shield, ShieldAlert, ShieldCheck, Shuffle, Smartphone,
  Target, Terminal, Ticket, TrendingUp, Trophy, Upload, User, UserCheck, UserCog, Users, Wallet, Wifi,
  WifiOff, Workflow, XCircle, Zap, type LucideIcon, type LucideProps,
} from "lucide-react";
import type { IconName } from "@/types";

const icons: Record<IconName, LucideIcon> = {
  shield: Shield,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  lock: Lock,
  key: KeyRound,
  qr: QrCode,
  ticket: Ticket,
  "credit-card": CreditCard,
  wallet: Wallet,
  landmark: Landmark,
  receipt: Receipt,
  database: Database,
  server: Server,
  cloud: Cloud,
  cpu: Cpu,
  network: Network,
  globe: Globe,
  smartphone: Smartphone,
  scan: ScanLine,
  camera: Camera,
  wifi: Wifi,
  "wifi-off": WifiOff,
  radio: Radio,
  gate: DoorOpen,
  stadium: Goal,
  map: Map,
  users: Users,
  user: User,
  "user-check": UserCheck,
  "user-cog": UserCog,
  badge: BadgeCheck,
  gauge: Gauge,
  activity: Activity,
  "bar-chart": BarChart3,
  "pie-chart": PieChart,
  "trending-up": TrendingUp,
  clipboard: Clipboard,
  "clipboard-check": ClipboardCheck,
  "file-text": FileText,
  layers: Layers,
  boxes: Boxes,
  workflow: Workflow,
  "git-branch": GitBranch,
  "git-merge": GitMerge,
  route: Route,
  flag: Flag,
  calendar: Calendar,
  clock: Clock,
  "alert-triangle": AlertTriangle,
  "alert-octagon": OctagonAlert,
  "check-circle": CheckCircle2,
  "x-circle": XCircle,
  search: Search,
  eye: Eye,
  settings: Settings,
  refresh: RefreshCw,
  upload: Upload,
  download: Download,
  send: Send,
  bell: Bell,
  building: Building2,
  trophy: Trophy,
  target: Target,
  link: Link2,
  book: BookOpen,
  package: Package,
  terminal: Terminal,
  monitor: Monitor,
  hash: Hash,
  repeat: Repeat,
  shuffle: Shuffle,
  zap: Zap,
};

export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Cmp = icons[name];
  return <Cmp aria-hidden="true" {...props} />;
}
